### ISSUE TITLE
List index out of range pri premikanju zadnjega testa v check secret testih

### ISSUE THREAD

**Issue by vkriznar** [vkriznar/pronalUI#17]
Pri check equal tega errorja ne vrne, vendar mi deluje kot da se nič ne zgodi.

**Comment by rkozelj** [comment]
Problem pri secret in izpisu errorja je bil v tem, da se je printalo nekaj s check.equal testi, kar sem sedaj zakomentirala in tega errora ni več.

Opazila sem, da se ta napaka s premikanjem testov (to da se nič ne zgodi) dogaja tako pri secret in pri equal testih če so v skupini 11 ali več. Prav tako gumba za brisanje testov in pošiljanje v opis ne delujeta za teste v skupini 11 ali več. Nekje druge je problem, vendar trenutno ne vidim kje..

**Comment by rkozelj** [comment]
V programu main.py se sedaj v funkciji edit_test izpisujeta group_id in i, vsakič ko klikneš enega od teh gumbov pri testih, vendar številke, ki se izpišejo za teste v skupini 11 ali več niso pravilne..

11 skupina, ki bi se morala v ozadju obravnavat kot 10. po vrsti v seznamu, se obravnava kot 0ta, 12. se obravnava kot prva. Izgleda kot da iz podnaloga.html dobimo napačno številko skupine?
