### ISSUE TITLE
gumb ob oknu za preostale teste bi lahko premaknili gor, na isto višino kot je napis "preostali testi"

### ISSUE THREAD

**Issue by rkozelj** [vkriznar/pronalUI#22]

**Comment by rkozelj** [comment]
okno za preostale teste se lahko potem razširi v desno

**Comment by vkriznar** [comment]
To nebo dobro izgledalo, ker na nobeni spletni strani ni da bi bil gumb za nekaj shraniti nad poljem. Kvecjemu bi ga lahko postavili pod okno, kot je naprimer tu za komentiranje na gitu, ampak se meni zdi odvec ker tistih 200px sirine ne pomeni veliko

**Comment by rkozelj** [comment]
Ok. Čeprav pri equal in secret testih pa imamo gumba nad tabelama.

**Comment by vkriznar** [comment]
Meni se zdi da gre tisto za drugo stvar ker gre za gumb, ki shrani vse spremembe vnesene v tabelo, namesti pro dodajanju testov ki gre za no pac dodajanje testov. Mozno pa da gledam na to pristransko ker sem si jaz tako zamislil in mi tako pravilno izgleda, ceprav gre za isto stvar. Spremeni pa poglej kaj ti bolj izgleda.

**Comment by rkozelj** [comment]
Meni izgleda v redu, bolj me moti to da je okence za ostale teste ožje od ostalih oken, ampak lahko tut pustimo kot je.
Imam pa še predlog. Glede na to da je na vmesniku kar nekaj gumbov za shranit, bi bilo mogoče bolje, da bi imeli le en gumb (recimo nad tistimi 3 gumbi spodaj), ki bi shranil vse spremembe narejene na trenutni podnalogi (torej za vsa 4 okna in tudi spremembe na equal in secret testih), če je to možno naredit (in če se ti zdi, da bi izgledalo ok). Uporabnik bi tako rabil manj klikat.

**Comment by rkozelj** [comment]
je pa res, glede na to, da jse stran lahko razširi zelo navzdol, da bo potem uporabnik moral za eno majhno spremembo v besedilu skrolat do dol, da bo shranil.

**Comment by rkozelj** [comment]
Naredimo en gumb nad tistimi tremi gumbi spodaj, ki shrani vse spremembe na podnalogi
