### ISSUE TITLE
pop up na gumbu "oddaj nalogo", če spremembe niso shranjene

### ISSUE THREAD

**Issue by rkozelj** [vkriznar/pronalUI#23]

**Comment by rkozelj** [comment]
Verjetno bi bilo dobro to naredit tudi na gumbu "nova podnaloga", saj se neshranjene spremembe prav tako izgubijo, ko se vrneš na to podnalogo na kateri si kliknil gumb "nova podanaloga"

pop up za gumb "oddaj nalogo" je treba nardit na zavihkih s podnalogami in na zavihku z nalogo.

pop up za gumb "nova podnaloga" pa verjetno treba naredit le na zavihkih za podnaloge, saj se le te kar naprej osvežuejo, ko klikneš na njih, zavihek z nalogo se ne osvežuje kar naprej, tako da spremembe ostanejo

**Comment by vkriznar** [comment]
To na gumbu nova naloga ne rabimo več, saj sem sedaj popravil tako da ko pride tab v focus, se sedaj ne več osveži stran ampak se submita form. Za uporabnika se nič to ne spremeni on isto samo vidi kako se osveži stran vendar je to izjemno boljše saj se vse ne shranjene spremembe od prej sedaj shranijo.

**Comment by rkozelj** [comment]
super :)
Pop up se ne pojavi na gumbu "oddaj nalogo" na zavihku naloga

**Comment by vkriznar** [comment]
Aja, tam sem pozabil dodati, dodam takoj.

**Comment by rkozelj** [comment]
Pa opažam, da če recimo dodaš en equal test, ti tudi ne pusti oddat kar tko ampak te vpraša. Načeloma se ta sprememba sama od sebe shrani. Prav tako, če izbrišeš en test. Sicer je ok, ampak če lahko to odpraviš bi blo še bolš :)
Torej za gumbe briši test, ter premik gor in dol med testi se samo shrani, za gumb pošlji v opis pa ne

**Comment by vkriznar** [comment]
Saj ta gumb za oddaj nalogo ni vezan na to ali so kakšne neshranjene spremembe, ampak se vedno pojavi ko uporabnik hoče oddati nalogo, zato da preveri če tudi v drugih podnalogah nima kaj ne shranjenega.
