### ISSUE TITLE
Napisat bo treba navodila za uporabo vmesnika

### ISSUE THREAD

**Issue by rkozelj** [vkriznar/pronalUI#25]
Torej:

* da naj na datoteki, ki jo bodo odpri z vmesnikom (niti ne na vmesniku) znotraj svojih nizev ne uporabljajo """ (trojnih dvojnih narekovajev), ker že mi nize na koncu obdamo s temi narekovaji. So pa nizi lahko obdani s temi narekovaji - torej:
"""to je niz: 'sporočilo'""" je ok, 
'to je niz: """sporočilo"""' pa ni ok, 
sicer mi v ozadju vse """ spremenimo v ''', preden niz obdamo z """, vendar lahko pri določenih primerih vseeno pride do problemov (recimo, da uporabnik v nizu že uporablja ''', kjer bi nastopil problem, če bi mi kak drug niz znotraj že obstoječih ''', prav tako obdali z ''') - morda bi bilo še bolje, da sploh ne uporabljajo nobenih trojnih narekovajev?

* Prvi argument v Check.equal in drugi argument v check.secret se na vmesniku pišeta normalno, torej nista niza (saj mi to v ozadju že preoblikujemo v niz), medtem ko se mora drugi argument v check.equal, če je niz, tudi na vmesnik zapisati kot niz, torej obdan z nekimi narekovaji, saj mi tega v ozadju ne zapišemo kot niz!
npr, da preverjamo že ima spremenljivka y vrednost "rumena", Check.equal(y, "rumena"), mora "rumena" biti niz na vmesniku in ne le beseda rumena, če pa ima spremenljivka vrednost 3 pa je to pač 3.
Torej:
Check.equal: 1. arg na vmesniku ni nikoli niz, 2. arg na vmesniku je niz, če je res niz
Check.secret: 1. arg na vmesniku ni nikoli niz, 2. arg na vmesniku ni ni nikoli niz

* skupina na vmesniku pri equal in secret testih pomeni povezava z and (testi, ki so v isti skupini so povezani z and)

* številke na desni, pri equal in secret testih povedo, kateri po vrsti je ta test v posamezni skupini

* teste equal in secret se da spreminjati, tako, da na test kliknemo in ga uredimo, vendar se spremembe ne shranijo same od sebe, če želimo spremembe shranit, moramo kliknit gumb "shrani spremembe na/v podnalogi"

* gumbi na desni pri equal in secret testih (briši, premik gor, premik dol) tudi shranijo narejeno spremembo, torej ni potrebno spremembe še dodatno shranjevati, za gumb premik v opis je potrebno spremembo dodatno shraniti z gumbom "shrani spremembe na/v podnalogi"

* verjetno je treba razložit kaj pomeni da test pošljemo v opis -naredi se:
>>> zmnozi(3, 3)
9

* da naj z vmesnikom ne odpirajo datotek, kjer znotraj svojih nizev uporabljajo zaklepaje
-naš program ne dela za primere, kjer se v nizih pojavljajo zaklepaji, npr: Check.equal("""prestej_stevilo_znakov(")")"""), saj se test razbije narobe  - jih pa človek lahko piše na vmesnik, saj se napišejo ok, le sparsajo se narobe, medtem ko za oklepaje dela ok - taki testi gredo pod other

* gumb "shrani spremembe na/v podnalogi" shrani spremembe narejene v oknu za opis, pre-kodo, rešitev, ostale teste in spremembe, ki jih narediš, če spreminjaš že obstoječe equal in secret teste (to ne vključuje brisanja testov ter premikanje testov gor in dol  - te stvari se shranijo same ob kliku na te gumbe)

* razložit je treba kaj je prekoda (koda, ki uporabnika že čaka v podnalogi)

* ko se bo pisalo navodila je verjetno najbolje publiko vikat

* ker na gumbu za izbris podnaloge nimamo popup okna, ki uporabnika opozori, da bodo neshranjene spremembe na podnalogah izbrisane (ker bi bilo nadležno imeti toliko popup oken), mora uporabnik zelo pazit. Če recimo naredi spremembe na 4. podnalogi, ki jih ne shrani, nato pa gre brisat 3. podnalogo, se mu bodo lahko zaradi osveževanja podnalog, spremembe na podnalogah ki so > od tiste, ki jo je izbrisal, razveljavile.

* verjetno je potrebno povedat še kaj...

**Comment by MitjaR** [comment]
Done in README.md file.
