### ISSUE TITLE
Problem pri brisanju podnalog

### ISSUE THREAD

**Issue by rkozelj** [vkriznar/pronalUI#27]
ko izbrišeš neko podnalogo, ki ni zadnja, se pri osveževanju zadnje podnaloge pojavi error:
  File "D:\git\pronalUI\src\main.py", line 206, in podnaloga_post
    problem_part = problem.parts[part_num-1]
IndexError: list index out of range

**Comment by vkriznar** [comment]
Aja seveda, ker se sedaj submita form in ne refresha. in se submita na problemu ki ne obstaja.
