### ISSUE TITLE
morda bi morali imeti pop up tudi na gumbu "izbriši podnalogo"

### ISSUE THREAD

**Issue by rkozelj** [vkriznar/pronalUI#28]
Če je na fajlu recimo 5 nalog. Naredim spremembe na 3. podnalogi, ki jih ne shranim, nato izbrišem 2. podnalogo in se vrnem na zavihek od 3. podnaloge, kjer izgubim spremembe, ker se je stran osvežila.

Lahko pa stvar zapišemo med navodila za uporabo vmesnika, da naj pač človek pazi na to. Da ne bo za vsak gumb še svoj pop up (ker zna biti že kar nadležno).

**Comment by vkriznar** [comment]
Ja to bi bilo res malo preveč nadležno če bi vsak drugi gumb imel popup.

**Comment by vkriznar** [comment]
Prav tako, tisto kar si napisala ni res. Kot sem dejal prej sem to popravil da se stran ne odveži ampak se submita form. Sprobaj in boš videla, da se vse neshranjene spremembe shranijo. Tudi če imaš tako situacijo da narediš neshranjene spremembe na 3 podnalogi, izbrises 2. in gres nazaj na 3. bos videla, da se spremembe shranijo.

**Comment by rkozelj** [comment]
Kar sem napisala je res. Še vedno se to dogaja, na podnalogah, ki so večje od tiste, ki si jo izbirsal. Je pa res, da se je tudi pri meni pojavil primer, ko so spremembe ostale, vednar ne ostanejo vedno ! Malo poskušaj, boš videl.. se je pojavil tudi primer, ko so se po izbrisu 2. podnaloge spremembe na novi 3. nalogi ohranile, spremembe na novi 2. nalogi pa ne.
