### ISSUE TITLE
shranjevanje

### ISSUE THREAD

**Issue by rkozelj** [vkriznar/pronalUI#5]
treba je omogočiti shranjevanje testov in vseh ostalih oken...
pri testih bi bilo treba dostopati do vsakega polja v testu posebej, ker tisto z nizem ni lepa rešitev

**Comment by vkriznar** [comment]
Kaj bi bilo treba pri testih dostopati do vsakega polja v testu posebej?

**Comment by rkozelj** [comment]
ugotavljala sva, da to, da dobiš vse spremembe narejene na oknih v obliki niza, ki ga nato poskušaš sparsat z regularnimi izrazi, ni preveč dobra rešitev. To kar potem dobiš, poskušaš ločit po vejicah, vejice pa se lahko pojavljajo kjer koli...
Bolje bi bilo narediti kako drugače, se pravi, da teh sprememb ne bi dobil vseh naenkrat v obliki niza, ampak bi že takoj vedel, katera sprememba je prišla s katerega okna. Zato sva pol nardila tist gumb z disketo zraven vsakega testa, da bi se spremembe testov shranjevale za vsak test posebej, če že ne gre drugače. Bi pa pri tem mogu vedet, kaj je prišlo s katerega okna in ga primerno posodobit. Sva poskušala to naredit, pa nama ni ratalo.

**Comment by vkriznar** [comment]
Jst sm zej tko naredu, da se na brskalniku tko shranjujejo editi testov, da se atributi posamezne spremembe locjo z dvema dvopicjema, posamezne spremembe med sabo pa za dvopicjem in podpicjem (kle lah damo karkol pac, samo tko da lahko locmo posamezne spremembe notr). Pa to pol v pythonu splitamo. K serverju drugo kot string nemors parsat. Tkoda to kar sta vidva hotla narest bi mogl nakonc bit cist isto sparsan kot kar sm jst naredu, samo da je uporabnik bolj omejen, pa bi mislu da more vsak test posebi editat.

**Comment by MitjaR** [comment]
To je lahko le začasna rešitev, ki pa na primer za primer:
Check.Equal(prestej_vejice("""Ena, dva, tri."""), 2) ne dela.

**Comment by vkriznar** [comment]
Kaj, zakaj to nebi delal?

**Comment by vkriznar** [comment]
Mislm sploh nevem kaj stem hocs povedat, kaj bi ti v tabeli testov spremenu da bi blo povezan stem kar si ti napisu?

**Comment by rkozelj** [comment]
Mitja ti je podal primer, ko bi se tvoja metoda sesula, če bi imel nastavljeno, da se atributi posamezne spremembe ločjo z vejico (kot je bilo prej), sedaj ko si to spremenil v dva podpičja ter v dvopičje in podpičje bo pa problem recimo v primeru, da uporabnik sestavi funkcijo, ki sprejme nek niz in vrača število dvojnih podpičij:
Check.Equal(prestej_dvojna_podpicja("""Ena:: dva:: tri."""), 2)

Ali pa, če sestavi funkcijo, ki sprejme niz in vrne kolikokrat se v nizu zaporedoma pojavita dvopičje in podpičje:
Check.Equal(prestej("""Ena:; dva:; tri."""), 2)

Problem je v tem, da ne veš vnaprej kakšne nize boš dobival kot argumente v equal in secret testih in bo zato vedno lahko prišlo do primera, ko program ne bo deloval vredu.
V tabeli testov bi zato bilo dobro znat dostopat do okenc brez splitanja nizov. Ni dobro, da dobiš vsebino vseh oken naenkrat v obliki niza, ker ni varno da se sam vnaprej odločiš s katerim znakom jih boš ločil,  ker ne veš, kaj bo uporabnik vnesel notr, lahko da bo vnesel ravno ta znak oziroma kombinacijo znakov za katere si se ti odločil, da pomenijo nekaj drugega.

**Comment by vkriznar** [comment]
Ja dobr sej jih lahko ločmo z :;/=$#%€£¥&^%/= zarad mene. Lahko jih ločmo s celotno 7. kitico Zdravljice. Kar vidva hočta narest bi pomenl da bi vsaka sprememba testov sla na nov route in bi pomenl konstantno osveževanje strani, vsakič ko bi uporabnik neki popravu.

**Comment by rkozelj** [comment]
Se prav znaš dostopat do posameznih oken? 
Če mislš, da bo pol preveč osveževanja strani, ni treba, da se vsaka sprememba takoj, k se nardi tut shran, loh se shranjo spremembe za vsak test posebej, samo kadar uporabnik klikne tisto disketo ob testu. 

Samo bi res rada izognila temu, da se nardi nek niz in se ga pol splita. Ker tut če boš dal kr eno kombinacijo znakov za splitanje, to ni "lepa" rešitev. Je sicer zlo mal verjetno, da bo uporabnik točno tist podal, še vedno pa obstaja možnost, da bo.

**Comment by vkriznar** [comment]
Mislm da edin način da se izognemu splitanju je da bi uporabniku shrano vsako spremembo v polju posebi. Torej ce bi hotu spremenit en test bi rabu 3x shrant vsako posamezno spremembo polja. Kar je seveda neumn. Probita pogooglat pa se domislt kej novga. Sam men se zdi to da lahko v kateremkol polju spremeniš pa pol vse spremembe naenkrat shrans, pa ce to splitamo npr z nevem kombinacijo "€$%", to  z 99.99999% sigurnostjo uporabnik nebo v test zapisu. Vem da ni najlepš sam toj zaenkrat najboljš kar mamo.

**Comment by vkriznar** [comment]
Mogoče edin če bi parsu niz že sestavljen v js-tu, pa bi ga potem shranu v un value k se posta z shrani spremembe pa potem z unmu modulom v pythonu sam odstranu " ", sam nevem če se to da dat array v value. Na zacetku sm probov dat array v value z array to string js funkcijo vendar to ni ratal dobr. Probita mal.

**Comment by rkozelj** [comment]
Spreminjanje testov trenutno dela le za prvi test, ker je hard codano na i=0, ker ne znava dobit indexa od podnaloge (polja, ki je na novo na vmesniku) (i v main je index v podnaloga.html)


```
change = {
            "group_id" : $(this)[0].parentNode.parentNode.rowIndex,
            "expression" : $(this)[0].parentNode.cellIndex,
            "other" : $(this).html(),
            "index" : $(this)[0].parentNode // tole je treba popravt, ne znava dobit indexa vn (druga številka pr testu na vmesniku)
            };
```

**Comment by vkriznar** [comment]
Zaprl z commit #99, pozabu sm v commit message dodat to.
