### ISSUE TITLE
file_name mora dobiti directory od naložene datoteke, ne pa samo "../edit_files/"

### ISSUE THREAD

**Issue by vkriznar** [vkriznar/pronalUI#6]

**Comment by rkozelj** [comment]
saj dobi direcotory od naložene datoteke: "../edit_files/" + file_name, kje je file_name recimo "naloga_in.py" ?

**Comment by vkriznar** [comment]
Ne, zdej dobi samo naslov fila, če pa bi naprimer uploadu iz nekega drugega directorija npr. D:\Downloads, potem se mu cel program sesuje.

**Comment by rkozelj** [comment]
to bi se mogl nekak spremenit, da vrača celotno pot fajla:
file = request.files.get('file')

**Comment by vkriznar** [comment]
Žal tega brskalniki ne pustijo. Treba bo delati z file.file, kot je tam že nekaj zakomentirano, treba bo uploadan file poslati in ga prebrati z Problem/ProblemPart.py

**Comment by rkozelj** [comment]
Mislim, da sedaj dela.
