### ISSUE TITLE
brisanje podnalog

### ISSUE THREAD

**Issue by rkozelj** [vkriznar/pronalUI#7]
Če so na fajlu recimo 3 podnaloge in izbrišeš recimo drugo, stvar dela, če pa nato poskušaš izbrisat še tretjo podnalogo se pa stvar sesuje, ker na datoteki niso več tri podnaloge ampak le še dve in je tako problem.parts[part_num-1] že izven seznama. 
Treba bi bilo preoštevilčit vse podnaloge, ki imajo višje številke od tiste podnaloge, ki si jo lihkar izbrisal.

**Comment by vkriznar** [comment]
To sm že jst popravu sam rabm neki še dodelat.

**Comment by rkozelj** [comment]
Supr :)

**Comment by vkriznar** [comment]
Commit #90 to do neke mere poprav. Kar se nardi je, da ko uporabnik izbriše nalogo ga potem iz višjih podnalog redirecta na eno manj. To se zgodi torej ko uporabnik osveži stran, vendar pa ker uporabnik lahko pozab osvežit stran sm dodal še funkcijo, ki vsakič ko uporabnik klikne na en tab se mu ta osveži. Tako da ga automatično redirecta. Vendar pa nevem zakaj ampak kdaj se ta automatičn refresh ne zgodi. Lahko mal probaš pa če se ti kej dozdeva zakaj se to vedno ne zgodi, sam gre pa to za js kodo.

**Comment by vkriznar** [comment]
Bom pa zaenkrat pustu še odprt issue, da bomo vedel.

**Comment by vkriznar** [comment]
Okej tist kar sm zgor omenjov, se samo zgodi samo v primeru, ko izbrišeš 1. podnalogo in greš na 2. podnalogo, 2. podnaloge ne osvež. Mal se mi zdi čudn to. K npr. če pa izbrišeš 2. se 3. čisto lepo osveži, prav tako če iz 1.podnaloge klikneš na 3. se potem ta osveži na prvo podnalogo.

**Comment by rkozelj** [comment]
Trenutno je problem, da se naloge ne osvežijo v pravilnem vrstnem redu, oziroma se pri osvežitvi menja vrsti red.

Part_num se verjetno dobi iz napisa na zavihku, kar je potem še drugje narobe, če se na zavihku ne popravi pravilno.

Če ni nobene podnaloge več (si izbrisal vse) je tut error.

**Comment by rkozelj** [comment]
Če izbrišem 1. podnalogo in kliknem na zavihek od 2. podnaloge, se ta preimenuje v 1. in če nato kliknem na zavihek od 3. podnaloge, se ta preimenuje v 2., kar je ok.

Če pa najprej kliknem na zavihek od 3. podnaloge, se pa ta preimenuje v 1. , 2. pa ostane 2. ! To se ne bi smel zgodit, vedno bi mogle it številke za ena dol. Ne bi smel bit odvisno od tega, kam človek klika.

**Comment by vkriznar** [comment]
Aha ok, imaš prov.
